Run("notepad.exe")
WinWait("[CLASS:Notepad]")
ControlSetText("[CLASS:Notepad]", "", "Edit1", "放点文本进去")
Local $sText = ControlGetText("[CLASS:Notepad]", "", "Edit1")
MsgBox(0, "ControlGetText 例子", "控件文本为: " & $sText)